### ISSUE TITLE
Gmail doesn't load since version 0.1621

### ISSUE THREAD

**Issue by hjsleijster** [Swingline0/openMultiLogin#6]
Dev Tools gives this error when visiting mail.google.com :
Uncaught CustomError: Error in protected function: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
        c @ rs=AHGWq9AlZkoBm_7ifpa6LevzhWaPN8Ovcw:181
        fe.Rb @ rs=AHGWq9AlZkoBm_7ifpa6LevzhWaPN8Ovcw:159

**Comment by altwohill** [comment]
I'm also getting this issue

**Comment by EranSch** [comment]
Thanks Guys. A user recently noticed that there was still some obfuscated code in `content.js` - I was able to restore it but missed a wrapping IIFE which seemed to open the door for some scope related weirdness. I'm going to push v0.1622 up to the store now. 

Thanks again!

**Comment by EranSch** [comment]
Alrighty @hjsleijster @mobiusnz, the new version has been published to the store, and should propagate over the next few hours. 

Could you please confirm that the issue has or has not been resolved for you?

**Comment by hjsleijster** [comment]
Confirmed! Fix is working.

**Comment by hjsleijster** [comment]
There is still a "debugger;" in the code! Quite annoying.

**Comment by EranSch** [comment]
Sheesh, how embarrassing! That's why you don't deploy code at 4:30am...

I'll get a new build up when I wrap up at the gym.

**Comment by EranSch** [comment]
Removed the debugger in #9, going to deploy v0.1623 in a moment. Closing this issue now.
